import React, { useState } from 'react';
import { formatTokenAmount } from '@/lib/utils/formatters';
import { useRouter } from 'next/navigation';
import { Navbar } from '@/components/layout/Navbar';
import { AddLiquidity } from '@/components/liquidity/AddLiquidity';
import { RemoveLiquidity } from '@/components/liquidity/RemoveLiquidity';
import { CreatePool } from './CreatePool';
import { MyPositions } from './MyPositions';
import { PoolCard } from '@/components/ui/pool-card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { SolIcon, UsdcIcon, UsdtIcon, RushIcon, WethIcon } from '@/components/icons/TokenIcons';
import { AlertCircle, Plus, Search, Layers } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface Pool {
    id: string;
    name: string;
    tokens: [string, string]; // Fixed: changed from string[] to tuple
    address: string;
    tvl: number;
    apy: number;
    fee: number;
    volume24h: number;
    reserveA?: number;
    reserveB?: number;
    formattedReserveA?: string;
    formattedReserveB?: string;
    tokenADecimals?: number;
    tokenBDecimals?: number;
}

interface PoolsViewProps {
    pools: Pool[];
    loading?: boolean;
    error?: string | null;
    isUsingMockData?: boolean;
    handleAddLiquidity: (poolName: string) => void;
    onRefresh?: () => void;
}

const getTokenIcon = (symbol: string) => {
    switch (symbol) {
        case 'SOL': return <SolIcon className="w-8 h-8" />;
        case 'USDC': return <UsdcIcon className="w-8 h-8" />;
        case 'USDT': return <UsdtIcon className="w-8 h-8" />;
        case 'RUSH': return <RushIcon className="w-8 h-8" />;
        case 'WETH': return <WethIcon className="w-8 h-8" />;
        default: return <span className="text-2xl">?</span>;
    }
};

export const PoolsView: React.FC<PoolsViewProps> = ({
    pools,
    loading = false,
    error = null,
    isUsingMockData = false,
    handleAddLiquidity,
    onRefresh,
}) => {
    const router = useRouter();
    // FIXED: Add pool selector state for Add/Remove Liquidity tabs
    const [selectedPoolIndex, setSelectedPoolIndex] = useState(0);

    // Search and filter state
    const [searchQuery, setSearchQuery] = useState('');
    const [sortBy, setSortBy] = useState<'tvl' | 'apy' | 'volume' | 'fee'>('tvl');
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');



    const updatedAt = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    return (
        <div className="min-h-screen bg-[#F8FAFC] dark:bg-[#0B0E14] transition-colors duration-200 selection:bg-[#8B5CF6]/20">
            <Navbar />

            {/* Main Content */}
            <main className="relative z-10 max-w-7xl mx-auto px-6 pt-24 pb-12">
                {/* Status Banner */}
                {isUsingMockData && (
                    <div className="mb-6 p-3 bg-[#F1F5F9] dark:bg-[#161C2D] border border-[#E2E8F0] dark:border-white/10 rounded-lg flex items-center gap-2">
                        <AlertCircle className="w-4 h-4 text-[#9CA3AF]" />
                        <span className="text-sm text-[#475569] dark:text-[#9CA3AF]">
                            Using demo data. Deploy contracts to see real pools.
                        </span>
                    </div>
                )}

                {error && (
                    <div className="mb-6 p-3 bg-[#F1F5F9] dark:bg-[#161C2D] border border-[#E2E8F0] dark:border-white/10 rounded-lg flex items-center gap-2">
                        <AlertCircle className="w-4 h-4 text-[#9CA3AF]" />
                        <span className="text-sm text-[#475569] dark:text-[#9CA3AF]">
                            Pools are unavailable right now. Please try again shortly.
                        </span>
                    </div>
                )}
                {/* Header */}
                <div className="text-center mb-8">
                    <div className="flex items-center justify-between mb-4">
                        <h1 className="text-4xl sm:text-5xl font-semibold text-[#0F172A] dark:text-[#E5E7EB] tracking-tight">
                            Liquidity Pools
                        </h1>
                        <Button
                            onClick={() => router.push('/pools/new-position')}
                            className="bg-[#8B5CF6] hover:bg-[#7C3AED] text-white gap-2"
                        >
                            <Plus className="w-5 h-5" />
                            New Position
                        </Button>
                    </div>
                    <p className="text-[#475569] dark:text-[#9CA3AF] text-base sm:text-lg max-w-2xl mx-auto">
                        Provide liquidity to earn trading fees and protocol rewards.
                    </p>
                    <p className="text-sm text-[#94A3B8] dark:text-[#6B7280] mt-3">
                        Liquidity providers earn a proportional share of fees generated by swaps routed through each pool.
                    </p>
                </div>

                {/* Protocol Stats */}
                <div className="mb-10 rounded-2xl border border-[#E2E8F0] dark:border-white/10 bg-white dark:bg-[#121826] p-6 transition-colors duration-200">
                    <div className="flex items-center justify-between mb-4">
                        <h2 className="text-sm font-semibold text-[#0F172A] dark:text-[#E5E7EB]">Protocol Statistics</h2>
                        <span className="text-xs text-[#94A3B8] dark:text-[#6B7280]">Updated {updatedAt}</span>
                    </div>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                        <div title="Total capital locked across all pools.">
                            <div className="text-xs text-[#94A3B8] dark:text-[#6B7280] mb-2">TVL</div>
                            <div className="text-xl font-semibold text-[#0F172A] dark:text-[#E5E7EB] tabular-nums">
                                ${pools.reduce((sum, p) => sum + p.tvl, 0).toLocaleString()}
                            </div>
                        </div>
                        <div title="Total trading volume over the last 24 hours.">
                            <div className="text-xs text-[#94A3B8] dark:text-[#6B7280] mb-2">24h Volume</div>
                            <div className="text-xl font-semibold text-[#0F172A] dark:text-[#E5E7EB] tabular-nums">
                                ${pools.reduce((sum, p) => sum + p.volume24h, 0).toLocaleString()}
                            </div>
                        </div>
                        <div title="Number of active liquidity pools.">
                            <div className="text-xs text-[#94A3B8] dark:text-[#6B7280] mb-2">Active Pools</div>
                            <div className="text-xl font-semibold text-[#0F172A] dark:text-[#E5E7EB] tabular-nums">{pools.length}</div>
                        </div>
                        <div title="Average APY calculated from realized fees over 7 days.">
                            <div className="text-xs text-[#94A3B8] dark:text-[#6B7280] mb-2">Average APY</div>
                            <div className="text-xl font-semibold text-[#0F172A] dark:text-[#E5E7EB] tabular-nums">
                                {pools.length > 0
                                    ? (pools.reduce((sum, p) => sum + p.apy, 0) / pools.length).toFixed(1)
                                    : '0.0'}
                                %
                            </div>
                        </div>
                    </div>
                </div>

                <Tabs defaultValue="browse" className="w-full">
                    <TabsList className="grid w-full grid-cols-5">
                        <TabsTrigger value="browse">Browse Pools</TabsTrigger>
                        <TabsTrigger value="create">Create Pool</TabsTrigger>
                        <TabsTrigger value="positions">My Positions</TabsTrigger>
                        <TabsTrigger value="add">Add Liquidity</TabsTrigger>
                        <TabsTrigger value="remove">Remove Liquidity</TabsTrigger>
                    </TabsList>

                    {/* Browse Pools Tab */}
                    <TabsContent value="browse" className="space-y-6 mt-8">
                        {/* Search and Filter Bar */}
                        <div className="flex flex-col md:flex-row gap-4">
                            {/* Search Input */}
                            <div className="flex-1 relative">
                                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-[#94A3B8] dark:text-[#6B7280]" />
                                <input
                                    type="text"
                                    placeholder="Search pools by token symbol..."
                                    value={searchQuery}
                                    onChange={(e) => setSearchQuery(e.target.value)}
                                    className="w-full bg-white dark:bg-[#121826] border border-[#E2E8F0] dark:border-white/10 rounded-xl pl-12 pr-4 py-3 text-[#0F172A] dark:text-[#E5E7EB] placeholder:text-[#94A3B8] dark:placeholder:text-[#6B7280] focus:outline-none focus:ring-2 focus:ring-[#8B5CF6] transition-colors duration-200"
                                />
                            </div>

                            {/* Sort Dropdown */}
                            <select
                                value={sortBy}
                                onChange={(e) => setSortBy(e.target.value as any)}
                                className="bg-white dark:bg-[#121826] border border-[#E2E8F0] dark:border-white/10 rounded-xl px-4 py-3 text-[#0F172A] dark:text-[#E5E7EB] focus:outline-none focus:ring-2 focus:ring-[#8B5CF6] transition-colors duration-200"
                            >
                                <option value="tvl" className="bg-white dark:bg-[#121826]">Sort by TVL</option>
                                <option value="apy" className="bg-white dark:bg-[#121826]">Sort by APY</option>
                                <option value="volume" className="bg-white dark:bg-[#121826]">Sort by Volume</option>
                                <option value="fee" className="bg-white dark:bg-[#121826]">Sort by Fee</option>
                            </select>

                            {/* Sort Direction Button */}
                            <Button
                                variant="outline"
                                onClick={() => setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc')}
                                className="px-4"
                            >
                                {sortDirection === 'desc' ? '↓' : '↑'}
                            </Button>
                        </div>

                        {loading ? (
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                {Array.from({ length: 6 }).map((_, idx) => (
                                    <div
                                        key={idx}
                                        className="h-56 rounded-2xl border border-[#E2E8F0] dark:border-white/10 bg-white dark:bg-[#121826]"
                                    />
                                ))}
                            </div>
                        ) : pools.length === 0 ? (
                            <div className="text-center py-16">
                                <Layers className="w-12 h-12 text-[#94A3B8] dark:text-[#6B7280] mx-auto mb-4" />
                                <p className="text-[#475569] dark:text-[#9CA3AF] text-lg">No pools are live yet.</p>
                                <p className="text-[#94A3B8] dark:text-[#6B7280] text-sm mt-2">
                                    Create the first pool to bootstrap liquidity and earn early fees.
                                </p>
                                <Button
                                    onClick={() => router.push('/pools/new-position')}
                                    className="mt-4 bg-[#8B5CF6] hover:bg-[#7C3AED] text-white"
                                >
                                    Create Pool
                                </Button>
                            </div>
                        ) : (() => {
                            // Filter and sort pools
                            let filteredPools = pools.filter(pool => {
                                if (!searchQuery) return true;
                                const query = searchQuery.toLowerCase();
                                return pool.tokens[0].toLowerCase().includes(query) ||
                                    pool.tokens[1].toLowerCase().includes(query) ||
                                    pool.name.toLowerCase().includes(query);
                            });

                            // Sort pools
                            filteredPools = [...filteredPools].sort((a, b) => {
                                let aVal = 0, bVal = 0;
                                switch (sortBy) {
                                    case 'tvl':
                                        aVal = a.tvl;
                                        bVal = b.tvl;
                                        break;
                                    case 'apy':
                                        aVal = a.apy;
                                        bVal = b.apy;
                                        break;
                                    case 'volume':
                                        aVal = a.volume24h;
                                        bVal = b.volume24h;
                                        break;
                                    case 'fee':
                                        aVal = a.fee;
                                        bVal = b.fee;
                                        break;
                                }
                                return sortDirection === 'desc' ? bVal - aVal : aVal - bVal;
                            });

                            if (filteredPools.length === 0) {
                                return (
                                    <div className="text-center py-12">
                                        <Search className="w-12 h-12 text-[#94A3B8] dark:text-[#6B7280] mx-auto mb-4" />
                                        <p className="text-[#475569] dark:text-[#9CA3AF] text-lg">No pools match your search</p>
                                        <Button
                                            variant="ghost"
                                            onClick={() => setSearchQuery('')}
                                            className="mt-4 text-[#8B5CF6]"
                                        >
                                            Clear search
                                        </Button>
                                    </div>
                                );
                            }

                            return (
                                <>
                                    <div className="text-sm text-[#94A3B8] dark:text-[#6B7280] mb-4">
                                        Showing {filteredPools.length} of {pools.length} pools
                                    </div>
                                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                        {filteredPools.map((pool) => (
                                            <PoolCard
                                                key={pool.id}
                                                poolAddress={pool.address}
                                                token1={{
                                                    symbol: pool.tokens[0],
                                                    icon: getTokenIcon(pool.tokens[0]),
                                                    reserve: formatTokenAmount(pool.reserveA || 0, 2, true),
                                                }}
                                                token2={{
                                                    symbol: pool.tokens[1],
                                                    icon: getTokenIcon(pool.tokens[1]),
                                                    reserve: formatTokenAmount(pool.reserveB || 0, 2, true),
                                                }}
                                                volume24h={pool.volume24h >= 1000000
                                                    ? `$${(pool.volume24h / 1000000).toFixed(2)}M`
                                                    : pool.volume24h >= 1000
                                                        ? `$${(pool.volume24h / 1000).toFixed(2)}K`
                                                        : `$${pool.volume24h.toFixed(2)}`
                                                }
                                                apy={`${pool.apy.toFixed(2)}%`}
                                                tvl={pool.tvl >= 1000000
                                                    ? `$${(pool.tvl / 1000000).toFixed(2)}M`
                                                    : pool.tvl >= 1000
                                                        ? `$${(pool.tvl / 1000).toFixed(2)}K`
                                                        : `$${pool.tvl.toFixed(2)}`
                                                }
                                                fee={`${pool.fee}%`}
                                                onViewDetails={() => router.push(`/pools/${pool.address}`)}
                                                onAddLiquidity={() => handleAddLiquidity(pool.name)}
                                            />
                                        ))}
                                    </div>
                                </>
                            );
                        })()}
                    </TabsContent>

                    {/* Create Pool Tab */}
                    <TabsContent value="create" className="mt-8">
                        <CreatePool />
                    </TabsContent>

                    {/* My Positions Tab */}
                    <TabsContent value="positions" className="mt-8">
                        <MyPositions pools={pools} loading={loading} onRefresh={onRefresh} />
                    </TabsContent>

                    {/* Add Liquidity Tab */}
                    <TabsContent value="add" className="mt-8">
                        <div className="flex flex-col items-center">
                            {/* Pool Selector */}
                            {pools.length > 1 && (
                                <div className="w-full max-w-lg mb-6">
                                    <label className="block text-sm font-medium text-[#475569] dark:text-[#9CA3AF] mb-2">
                                        Select Pool
                                    </label>
                                    <select
                                        value={selectedPoolIndex}
                                        onChange={(e) => setSelectedPoolIndex(Number(e.target.value))}
                                        className="w-full bg-white dark:bg-[#121826] border border-[#E2E8F0] dark:border-white/10 rounded-xl px-4 py-3 text-[#0F172A] dark:text-[#E5E7EB] focus:outline-none focus:ring-2 focus:ring-[#8B5CF6]"
                                    >
                                        {pools.map((pool, index) => (
                                            <option key={pool.address} value={index} className="bg-white dark:bg-[#121826]">
                                                {pool.tokens[0]}/{pool.tokens[1]} - TVL: ${pool.tvl.toLocaleString()}
                                            </option>
                                        ))}
                                    </select>
                                </div>
                            )}
                            {pools.length > 0 ? (
                                <AddLiquidity 
                                    poolAddress={pools[selectedPoolIndex]?.address || pools[0]?.address || ''} 
                                    onSuccess={onRefresh}
                                />
                            ) : (
                                <div className="text-center text-[#94A3B8] dark:text-[#6B7280] py-12">
                                    <Plus className="w-12 h-12 text-[#94A3B8] dark:text-[#6B7280] mx-auto mb-4" />
                                    <p className="text-lg text-[#475569] dark:text-[#9CA3AF]">Liquidity actions require an existing pool.</p>
                                    <p className="text-sm mt-2">Create or browse pools to continue.</p>
                                    <Button
                                        onClick={() => router.push('/pools/new-position')}
                                        className="mt-4 bg-[#8B5CF6] hover:bg-[#7C3AED] text-white"
                                    >
                                        Create Pool
                                    </Button>
                                </div>
                            )}
                        </div>
                    </TabsContent>

                    {/* Remove Liquidity Tab */}
                    <TabsContent value="remove" className="mt-8">
                        <div className="flex flex-col items-center">
                            {/* Pool Selector */}
                            {pools.length > 1 && (
                                <div className="w-full max-w-lg mb-6">
                                    <label className="block text-sm font-medium text-[#475569] dark:text-[#9CA3AF] mb-2">
                                        Select Pool
                                    </label>
                                    <select
                                        value={selectedPoolIndex}
                                        onChange={(e) => setSelectedPoolIndex(Number(e.target.value))}
                                        className="w-full bg-white dark:bg-[#121826] border border-[#E2E8F0] dark:border-white/10 rounded-xl px-4 py-3 text-[#0F172A] dark:text-[#E5E7EB] focus:outline-none focus:ring-2 focus:ring-[#8B5CF6]"
                                    >
                                        {pools.map((pool, index) => (
                                            <option key={pool.address} value={index} className="bg-white dark:bg-[#121826]">
                                                {pool.tokens[0]}/{pool.tokens[1]} - TVL: ${pool.tvl.toLocaleString()}
                                            </option>
                                        ))}
                                    </select>
                                </div>
                            )}
                            {pools.length > 0 ? (
                                <RemoveLiquidity 
                                    poolAddress={pools[selectedPoolIndex]?.address || pools[0]?.address || ''} 
                                    onSuccess={onRefresh}
                                />
                            ) : (
                                <div className="text-center text-[#94A3B8] dark:text-[#6B7280] py-12">
                                    <AlertCircle className="w-12 h-12 text-[#94A3B8] dark:text-[#6B7280] mx-auto mb-4" />
                                    <p className="text-lg text-[#475569] dark:text-[#9CA3AF]">Liquidity actions require an existing pool.</p>
                                    <p className="text-sm mt-2">Create or browse pools to continue.</p>
                                    <Button
                                        onClick={() => router.push('/pools')}
                                        className="mt-4 bg-[#8B5CF6] hover:bg-[#7C3AED] text-white"
                                    >
                                        Browse Pools
                                    </Button>
                                </div>
                            )}
                        </div>
                    </TabsContent>
                </Tabs>
            </main>
        </div>
    );
};
