import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import { createMint, mintTo, getAssociatedTokenAddress, createAssociatedTokenAccount } from '@solana/spl-token';
import * as fs from 'fs';
import { loadWallet, getRPC, formatNumber } from './utils';

/**
 * Create mock token mints for localnet testing
 */
async function createMockTokens(
    connection: Connection,
    payer: Keypair
): Promise<{
    usdcMint: PublicKey;
    usdtMint: PublicKey;
    rushMint: PublicKey;
}> {
    console.log('📝 Creating mock token mints for Localnet...\n');

    // Create USDC mint (6 decimals)
    console.log('  Creating Mock USDC mint...');
    const usdcMint = await createMint(
        connection,
        payer,
        payer.publicKey,
        null,
        6
    );
    console.log(`  ✓ USDC Mint: ${usdcMint.toBase58()}\n`);

    // Create USDT mint (6 decimals)
    console.log('  Creating Mock USDT mint...');
    const usdtMint = await createMint(
        connection,
        payer,
        payer.publicKey,
        null,
        6
    );
    console.log(`  ✓ USDT Mint: ${usdtMint.toBase58()}\n`);

    // Create RUSH mint (6 decimals)
    console.log('  Creating Mock RUSH mint...');
    const rushMint = await createMint(
        connection,
        payer,
        payer.publicKey,
        null,
        6
    );
    console.log(`  ✓ RUSH Mint: ${rushMint.toBase58()}\n`);

    return { usdcMint, usdtMint, rushMint };
}

async function getOrCreateTokenAccount(
    connection: Connection,
    payer: Keypair,
    mint: PublicKey,
    owner: PublicKey
): Promise<PublicKey> {
    const associatedToken = await getAssociatedTokenAddress(mint, owner);
    try {
        await connection.getTokenAccountBalance(associatedToken);
    } catch (e) {
        // Account doesn't exist, create it
        await createAssociatedTokenAccount(
            connection,
            payer,
            mint,
            owner
        );
    }
    return associatedToken;
}

/**
 * Mint test tokens to the wallet
 */
async function mintTestTokens(
    connection: Connection,
    payer: Keypair,
    mints: {
        usdcMint: PublicKey;
        usdtMint: PublicKey;
        rushMint: PublicKey;
    }
): Promise<void> {
    console.log('💰 Minting test tokens to wallet...\n');

    const mintToken = async (mint: PublicKey, symbol: string, amount: number) => {
        const ata = await getOrCreateTokenAccount(connection, payer, mint, payer.publicKey);
        
        // Mint tokens
        await mintTo(
            connection,
            payer,
            mint,
            ata,
            payer,
            amount
        );
        
        console.log(`  ✓ Minted ${formatNumber(amount / 1e6)} ${symbol}`);
    };

    // Mint 10,000 of each
    const amount = 10000 * 1e6;
    await mintToken(mints.usdcMint, 'USDC', amount);
    await mintToken(mints.usdtMint, 'USDT', amount);
    await mintToken(mints.rushMint, 'RUSH', amount);
    
    console.log();
}

/**
 * Main setup function
 */
async function main() {
    // Force localnet for this script
    const RPC_URL = 'http://127.0.0.1:8899';
    const connection = new Connection(RPC_URL, 'confirmed');
    const payer = loadWallet();

    console.log('\n=================================');
    console.log('🚀 SolRush Localnet Setup');
    console.log('=================================\n');
    console.log(`Wallet: ${payer.publicKey.toBase58()}`);
    console.log(`RPC: ${RPC_URL}\n`);

    try {
        const version = await connection.getVersion();
        console.log(`  ✓ Connected to validator: ${version['solana-core']}\n`);
    } catch (e) {
        console.log('❌ Could not connect to local validator!');
        console.log('   Run: solana-test-validator\n');
        process.exit(1);
    }

    // Airdrop SOL if low
    const balance = await connection.getBalance(payer.publicKey);
    console.log(`SOL Balance: ${balance / 1e9} SOL`);

    if (balance < 5 * 1e9) {
        console.log('  Requesting airdrop...');
        const signature = await connection.requestAirdrop(payer.publicKey, 10 * 1e9);
        await connection.confirmTransaction(signature);
        console.log('  ✓ Airdropped 10 SOL\n');
    } else {
        console.log('  ✓ Sufficient SOL\n');
    }

    // Step 1: Create token mints
    const mints = await createMockTokens(connection, payer);

    // Step 2: Mint test tokens
    await mintTestTokens(connection, payer, mints);

    // Step 3: Save mints to .env.local
    console.log('💾 Saving configuration...\n');

    // Try to keep existing program ID if possible, or use a default
    const programId = process.env.NEXT_PUBLIC_PROGRAM_ID || 'FZ25GUwrX9W5PxBe5Ep8fR1F3HzoSeGH61YvW8sBA8J1';

    console.log('  Creating Mock WETH mint for completeness...');
    const wethMint = await createMint(connection, payer, payer.publicKey, null, 9);
    console.log(`  ✓ WETH Mint: ${wethMint.toBase58()}\n`);


    const envContent = `# Generated by setup-local.ts on ${new Date().toISOString()}
NEXT_PUBLIC_NETWORK=localnet
NEXT_PUBLIC_RPC_URL=${RPC_URL}
NEXT_PUBLIC_PROGRAM_ID=${programId}
NEXT_PUBLIC_SOL_MINT=So11111111111111111111111111111111111111112
NEXT_PUBLIC_USDC_MINT=${mints.usdcMint.toBase58()}
NEXT_PUBLIC_USDT_MINT=${mints.usdtMint.toBase58()}
NEXT_PUBLIC_RUSH_MINT=${mints.rushMint.toBase58()}
NEXT_PUBLIC_WETH_MINT=${wethMint.toBase58()}
`;

    fs.writeFileSync('.env.local', envContent);
    console.log('  ✓ Saved to .env.local\n');

    console.log('=================================');
    console.log('✅ Setup Complete!');
    console.log('=================================\n');
    console.log('Next steps:\n');
    console.log('  1. Restart your Next.js app to pick up new env vars:');
    console.log('     Ctrl+C, then npm run dev\n');
}

main().catch((error) => {
    console.error('\n❌ Error:', error.message);
    process.exit(1);
});
