#!/usr/bin/env ts-node
import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import { createMint, mintTo, getOrCreateAssociatedTokenAddress } from '@solana/spl-token';
import * as fs from 'fs';
import { loadWallet, getRPC, formatNumber } from './utils';

/**
 * Create mock token mints for devnet testing
 */
async function createMockTokens(
    connection: Connection,
    payer: Keypair
): Promise<{
    usdcMint: PublicKey;
    usdtMint: PublicKey;
    rushMint: PublicKey;
}> {
    console.log('📝 Creating mock token mints...\n');

    // Create USDC mint (6 decimals)
    console.log('  Creating USDC mint...');
    const usdcMint = await createMint(
        connection,
        payer,
        payer.publicKey,
        null,
        6
    );
    console.log(`  ✓ USDC Mint: ${usdcMint.toBase58()}\n`);

    // Create USDT mint (6 decimals)
    console.log('  Creating USDT mint...');
    const usdtMint = await createMint(
        connection,
        payer,
        payer.publicKey,
        null,
        6
    );
    console.log(`  ✓ USDT Mint: ${usdtMint.toBase58()}\n`);

    // Create RUSH mint (6 decimals)
    console.log('  Creating RUSH mint...');
    const rushMint = await createMint(
        connection,
        payer,
        payer.publicKey,
        null,
        6
    );
    console.log(`  ✓ RUSH Mint: ${rushMint.toBase58()}\n`);

    return { usdcMint, usdtMint, rushMint };
}

/**
 * Mint test tokens to the wallet
 */
async function mintTestTokens(
    connection: Connection,
    payer: Keypair,
    mints: {
        usdcMint: PublicKey;
        usdtMint: PublicKey;
        rushMint: PublicKey;
    }
): Promise<void> {
    console.log('💰 Minting test tokens to wallet...\n');

    // Mint USDC
    const usdcAccount = await getOrCreateAssociatedTokenAddress(
        connection,
        payer,
        mints.usdcMint,
        payer.publicKey
    );
    await mintTo(
        connection,
        payer,
        mints.usdcMint,
        usdcAccount,
        payer,
        1000000 * 1e6 // 1M USDC
    );
    console.log(`  ✓ Minted ${formatNumber(1000000)} USDC`);

    // Mint USDT
    const usdtAccount = await getOrCreateAssociatedTokenAddress(
        connection,
        payer,
        mints.usdtMint,
        payer.publicKey
    );
    await mintTo(
        connection,
        payer,
        mints.usdtMint,
        usdtAccount,
        payer,
        1000000 * 1e6 // 1M USDT
    );
    console.log(`  ✓ Minted ${formatNumber(1000000)} USDT`);

    // Mint RUSH
    const rushAccount = await getOrCreateAssociatedTokenAddress(
        connection,
        payer,
        mints.rushMint,
        payer.publicKey
    );
    await mintTo(
        connection,
        payer,
        mints.rushMint,
        rushAccount,
        payer,
        10000000 * 1e6 // 10M RUSH
    );
    console.log(`  ✓ Minted ${formatNumber(10000000)} RUSH\n`);
}

/**
 * Main setup function
 */
async function main() {
    const RPC_URL = getRPC();
    const connection = new Connection(RPC_URL, 'confirmed');
    const payer = loadWallet();

    console.log('\n=================================');
    console.log('🚀 SolRush Devnet Setup');
    console.log('=================================\n');
    console.log(`Wallet: ${payer.publicKey.toBase58()}`);
    console.log(`RPC: ${RPC_URL}\n`);

    // Check SOL balance
    const balance = await connection.getBalance(payer.publicKey);
    console.log(`SOL Balance: ${balance / 1e9} SOL`);

    if (balance < 1e9) {
        console.log('\n⚠️  Low SOL balance!');
        console.log('Get devnet SOL: solana airdrop 2\n');
        process.exit(1);
    }

    console.log('\n');

    // Step 1: Create token mints
    const mints = await createMockTokens(connection, payer);

    // Step 2: Mint test tokens
    await mintTestTokens(connection, payer, mints);

    // Step 3: Save mints to .env.local
    console.log('💾 Saving configuration...\n');

    const programId = process.env.NEXT_PUBLIC_PROGRAM_ID || 'BJfcNtEyhU4wArQsyXkHZ9jmR7KD7KPHAGUwUySNnA5z';

    const envContent = `# Generated by setup-devnet.ts on ${new Date().toISOString()}
NEXT_PUBLIC_NETWORK=devnet
NEXT_PUBLIC_RPC_URL=${RPC_URL}
NEXT_PUBLIC_PROGRAM_ID=${programId}
NEXT_PUBLIC_USDC_MINT=${mints.usdcMint.toBase58()}
NEXT_PUBLIC_USDT_MINT=${mints.usdtMint.toBase58()}
NEXT_PUBLIC_RUSH_MINT=${mints.rushMint.toBase58()}
`;

    fs.writeFileSync('.env.local', envContent);
    console.log('  ✓ Saved to .env.local\n');

    console.log('=================================');
    console.log('✅ Setup Complete!');
    console.log('=================================\n');
    console.log('Next steps:\n');
    console.log('  1. Initialize RUSH rewards:');
    console.log('     npm run init:rush\n');
    console.log('  2. Create initial pool:');
    console.log('     npm run init:pool -- SOL USDC 100 10000\n');
    console.log('  3. Start the app:');
    console.log('     npm run dev\n');
}

main().catch((error) => {
    console.error('\n❌ Error:', error.message);
    process.exit(1);
});
